changes

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -15,6 +15,13 @@ jobs:
         env:
             BRANCH_NAME: ${{ inputs.branchName }}
         steps:
+            - name: Ensure running on main or master branch
+              run: |
+                if [[ "${GITHUB_REF##*/}" == "main" || "${GITHUB_REF##*/}" == "master" ]]; then
+                  echo "This workflow can´t only run on the 'main' or 'master' branch."
+                  exit 1
+                fi
+                
             - name: branch seleted
               run: echo "branch is $BRANCH_NAME"
               
@@ -28,13 +35,17 @@ jobs:
                   java-version: 17
                   distribution: temurin
                   cache: maven
-            # - name: build with maven
-            #   run: |
-            #       mvn clean install
+
             - name: Get version from pom.xml
               id: get_version
               run: |
                 VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
                 echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV
+              
             - name: Print project version
               run: echo "The project version is ${{ env.PROJECT_VERSION }}"
+              
+            - name: build with maven
+              run: |
+                  mvn clean install
+            
